# Generated by Django 5.1.5 on 2025-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_book_bottext_methodic_shortmethodic_task_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortmethodic',
            name='material',
            field=models.FileField(null=True, upload_to='short_methodics/'),
        ),
    ]
