# Generated by Django 5.1.5 on 2025-02-06 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_sendmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('message', models.TextField()),
                ('time_of_day', models.CharField(choices=[('утро', 'Утро'), ('вечер', 'Вечер')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DialogResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dialog_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dialogtask')),
            ],
        ),
    ]
