# Generated by Django 5.1.5 on 2025-02-06 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_dialogtask_dialogresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bottext',
            options={'verbose_name': 'Текст бота', 'verbose_name_plural': 'Тексты бота'},
        ),
        migrations.AlterModelOptions(
            name='dialogresponse',
            options={'verbose_name': 'Ответ на диалог', 'verbose_name_plural': 'Ответы на диалоги'},
        ),
        migrations.AlterModelOptions(
            name='dialogtask',
            options={'verbose_name': 'Ежедневное диалог-задание', 'verbose_name_plural': 'Ежедневные диалог-задания'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История покупок', 'verbose_name_plural': 'Истории покупок'},
        ),
        migrations.AlterModelOptions(
            name='methodic',
            options={'verbose_name': 'Методичка', 'verbose_name_plural': 'Методички'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Пользовательское уведомление', 'verbose_name_plural': 'Пользовательские уведомления'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка пользователя', 'verbose_name_plural': 'Оценки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='sendmessage',
            options={'verbose_name': 'Сообщение для рассылки', 'verbose_name_plural': 'Сообщения для рассылки'},
        ),
        migrations.AlterModelOptions(
            name='shortmethodic',
            options={'verbose_name': 'Краткая методичка', 'verbose_name_plural': 'Краткие методички'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Пользовательская подписка', 'verbose_name_plural': 'Пользовательские подписки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiondetails',
            options={'verbose_name': 'Тарифы подписок', 'verbose_name_plural': 'Тарифы подписок'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Глава и задания к ней', 'verbose_name_plural': 'Главы и задания к ним'},
        ),
        migrations.AlterModelOptions(
            name='tasksolved',
            options={'verbose_name': 'Решённое пользователем ызадание', 'verbose_name_plural': 'Решённые пользователем задания'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Выбранная пользователем тема', 'verbose_name_plural': 'Выбранные пользователем темы'},
        ),
        migrations.AlterModelOptions(
            name='themepool',
            options={'verbose_name': 'Доступные пользователю темы', 'verbose_name_plural': 'Доступные пользователю темы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена книги'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='dialogresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dialogresponse',
            name='dialog_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dialogtask', verbose_name='Задание диалога'),
        ),
        migrations.AlterField(
            model_name='dialogresponse',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='dialogresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dialogtask',
            name='day_number',
            field=models.IntegerField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='dialogtask',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='dialogtask',
            name='time_of_day',
            field=models.CharField(choices=[('утро', 'Утро'), ('вечер', 'Вечер')], max_length=10, verbose_name='Время дня'),
        ),
        migrations.AlterField(
            model_name='history',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='history',
            name='methodic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.methodic', verbose_name='Методичка'),
        ),
        migrations.AlterField(
            model_name='history',
            name='short_methodic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.shortmethodic', verbose_name='Краткая методичка'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='methodic',
            name='description',
            field=models.TextField(verbose_name='Описание методички'),
        ),
        migrations.AlterField(
            model_name='methodic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование методички'),
        ),
        migrations.AlterField(
            model_name='methodic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена методички'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='Текст уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TextField(null=True, verbose_name='Время уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='button_text',
            field=models.CharField(choices=[('option1', 'Нет кнопки'), ('option2', 'Кнопка на ЛК'), ('option3', 'Кнопка на задания'), ('option4', 'Кнопка на покупку книги'), ('option5', 'Кнопка на покупку методичек')], max_length=50, verbose_name='Тип кнопки'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='date_to_send',
            field=models.DateTimeField(verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='theme_all',
            field=models.BooleanField(default=False, verbose_name='Для всех тем'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='theme_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.themepool', verbose_name='Тип темы'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео 1'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео 2'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='video_3',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео 3'),
        ),
        migrations.AlterField(
            model_name='shortmethodic',
            name='description',
            field=models.TextField(verbose_name='Описание краткой методички'),
        ),
        migrations.AlterField(
            model_name='shortmethodic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование краткой методички'),
        ),
        migrations.AlterField(
            model_name='shortmethodic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена краткой методички'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscriptiondetails', verbose_name='Тариф подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Количество дней (по хорошему не менять)'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='description',
            field=models.TextField(verbose_name='Описание подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена подписки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number_of_chapter',
            field=models.IntegerField(verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='tasksolved',
            name='date_of_solving',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='tasksolved',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='tasksolved',
            name='text',
            field=models.TextField(default='', verbose_name='Текст решения'),
        ),
        migrations.AlterField(
            model_name='tasksolved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.themepool', verbose_name='Тип темы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='themepool',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название темы'),
        ),
    ]
