# Generated by Django 5.1.5 on 2025-02-10 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_book_options_alter_bottext_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subscriptiondetails', verbose_name='Тариф подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продление подписки',
                'verbose_name_plural': 'Продления подписок',
            },
        ),
    ]
