# Generated by Django 5.1.5 on 2025-02-11 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_subscriptionrenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.BooleanField(default=False, verbose_name='Совершил покупку')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный пользователь')),
                ('refer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший пользователь')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'unique_together': {('refer_user', 'invited_user')},
            },
        ),
    ]
