# Generated by Django 5.1.5 on 2025-02-16 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_refer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_send', models.DateTimeField(verbose_name='Дата отправки')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.book', verbose_name='Книга')),
                ('methodic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.methodic', verbose_name='Методичка')),
                ('short_methodic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.shortmethodic', verbose_name='Краткая методичка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на оценку',
                'verbose_name_plural': 'Запросы на оценку',
            },
        ),
    ]
